credentials:
  usernames:
    admin:
      email: lezcanojose7@gmail.com
      name: Administrador
      password: $2b$12$7Hau3E9byLFV2z6XRu4cl.7ROuCQgNX5A.pZDBQhTEGMeMJWbuBY2  # <--- Pegá el código largo que generaste en el Paso 2
      logged_in: False
    invitado:
      email: guest@vacamuerta.com
      name: Inversor Demo
      password: PEGAR_HASH_AQUI  # <--- Podés generar otro hash para este usuario si querés
      logged_in: False

cookie:
  expiry_days: 30
  key: random_signature_key  # Esto es para firmar la cookie, podés dejarlo así
  name: vaca_muerta_cookie